# Generated by Django 4.1.7 on 2023-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
