# Generated by Django 4.1.7 on 2023-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('credit_card', 'Carta di credito'), ('bank_transfer', 'Bonifico bancario')], default='paypal', max_length=20),
        ),
    ]
